//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Client.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string AuthMenu_SignIn {
            get {
                return ResourceManager.GetString("AuthMenu_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string AuthMenu_SignOut {
            get {
                return ResourceManager.GetString("AuthMenu_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My home.
        /// </summary>
        public static string AuthMenu_UserHome {
            get {
                return ResourceManager.GetString("AuthMenu_UserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post!.
        /// </summary>
        public static string Btn_Post {
            get {
                return ResourceManager.GetString("Btn_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register!.
        /// </summary>
        public static string Btn_Register {
            get {
                return ResourceManager.GetString("Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file or click to upload photo.
        /// </summary>
        public static string Darkroom_DropZoone {
            get {
                return ResourceManager.GetString("Darkroom_DropZoone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to register you in. Please, try one more time later..
        /// </summary>
        public static string EAPI_Auth_RegistrationError {
            get {
                return ResourceManager.GetString("EAPI_Auth_RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {UserName} is already taken. Please, select a different one..
        /// </summary>
        public static string EAPI_Auth_UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("EAPI_Auth_UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too big!.
        /// </summary>
        public static string EAPI_Image_FileTooBig {
            get {
                return ResourceManager.GetString("EAPI_Image_FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image dimensions are either too big or too small!.
        /// </summary>
        public static string EAPI_Image_SizeViolation {
            get {
                return ResourceManager.GetString("EAPI_Image_SizeViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have encountered an error, trying save your file :( Please, try one more time..
        /// </summary>
        public static string EAPI_Image_Unknown {
            get {
                return ResourceManager.GetString("EAPI_Image_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is not supported!.
        /// </summary>
        public static string EAPI_Image_UnsupportedFormat {
            get {
                return ResourceManager.GetString("EAPI_Image_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model state.
        /// </summary>
        public static string EAPI_InvalidModelState {
            get {
                return ResourceManager.GetString("EAPI_InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value(s) you provided is invalid!.
        /// </summary>
        public static string EAPI_InvalidValue {
            get {
                return ResourceManager.GetString("EAPI_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have encountered an error, while trying to execute your request :( Please, try one more time..
        /// </summary>
        public static string EAPI_Unknown {
            get {
                return ResourceManager.GetString("EAPI_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be min. {MinLength} and max. {MaxLength} characters long..
        /// </summary>
        public static string EAPI_ValueLength {
            get {
                return ResourceManager.GetString("EAPI_ValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, provide a value!.
        /// </summary>
        public static string EAPI_ValueRequired {
            get {
                return ResourceManager.GetString("EAPI_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters A-Z, a-z, numbers 0-9, dash and underscore are allowed! .
        /// </summary>
        public static string EC_Auth_InvalidUserName {
            get {
                return ResourceManager.GetString("EC_Auth_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken. Please, select a different one..
        /// </summary>
        public static string EC_Auth_UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("EC_Auth_UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name should be min. 2 and max. 20 characters long..
        /// </summary>
        public static string EC_Auth_UserNameLength {
            get {
                return ResourceManager.GetString("EC_Auth_UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is incomplete or not valid..
        /// </summary>
        public static string EC_Profile_InvalidEmail {
            get {
                return ResourceManager.GetString("EC_Profile_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ add ].
        /// </summary>
        public static string Exif_Empty {
            get {
                return ResourceManager.GetString("Exif_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  s.
        /// </summary>
        public static string Format_Exif_ExposureTime {
            get {
                return ResourceManager.GetString("Format_Exif_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  mm.
        /// </summary>
        public static string Format_Exif_FocalLength {
            get {
                return ResourceManager.GetString("Format_Exif_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f/{0}.
        /// </summary>
        public static string Format_Exif_FStop {
            get {
                return ResourceManager.GetString("Format_Exif_FStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  s.
        /// </summary>
        public static string Format_Exif_ShutterSpeed {
            get {
                return ResourceManager.GetString("Format_Exif_ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Hint_City {
            get {
                return ResourceManager.GetString("Hint_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country....
        /// </summary>
        public static string Hint_Country {
            get {
                return ResourceManager.GetString("Hint_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, provide your email.
        /// </summary>
        public static string Hint_EmailAddress {
            get {
                return ResourceManager.GetString("Hint_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name will be displayed instead of username.
        /// </summary>
        public static string Hint_FullName {
            get {
                return ResourceManager.GetString("Hint_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a story about this photo.
        /// </summary>
        public static string Hint_PhotoStory {
            get {
                return ResourceManager.GetString("Hint_PhotoStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s on your mind?.
        /// </summary>
        public static string Hint_WhatsOnYourMind {
            get {
                return ResourceManager.GetString("Hint_WhatsOnYourMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Label_Exif_CameraModel {
            get {
                return ResourceManager.GetString("Label_Exif_CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Label_Exif_Copyright {
            get {
                return ResourceManager.GetString("Label_Exif_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        public static string Label_Exif_DateTimeTaken {
            get {
                return ResourceManager.GetString("Label_Exif_DateTimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure.
        /// </summary>
        public static string Label_Exif_ExposureTime {
            get {
                return ResourceManager.GetString("Label_Exif_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal length.
        /// </summary>
        public static string Label_Exif_FocalLength {
            get {
                return ResourceManager.GetString("Label_Exif_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string Label_Exif_FStop {
            get {
                return ResourceManager.GetString("Label_Exif_FStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string Label_Exif_Iso {
            get {
                return ResourceManager.GetString("Label_Exif_Iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens.
        /// </summary>
        public static string Label_Exif_LensModel {
            get {
                return ResourceManager.GetString("Label_Exif_LensModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter speed.
        /// </summary>
        public static string Label_Exif_ShutterSpeed {
            get {
                return ResourceManager.GetString("Label_Exif_ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Label_FullName {
            get {
                return ResourceManager.GetString("Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile photo.
        /// </summary>
        public static string Label_ProfilePhoto {
            get {
                return ResourceManager.GetString("Label_ProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select your user name:.
        /// </summary>
        public static string Label_SelectUserName {
            get {
                return ResourceManager.GetString("Label_SelectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Label_Story {
            get {
                return ResourceManager.GetString("Label_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from?.
        /// </summary>
        public static string Label_WhereDoYouLive {
            get {
                return ResourceManager.GetString("Label_WhereDoYouLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MainMenu_Gallery {
            get {
                return ResourceManager.GetString("MainMenu_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a message for you, but we can&apos;t find it anymore :(.
        /// </summary>
        public static string MAPI_Fallback {
            get {
                return ResourceManager.GetString("MAPI_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having email address set up would help to resolve any problems with your profile if they happen. We will not send any promotion or other notifications until you allow us to do so..
        /// </summary>
        public static string ProfilePrivate_EmailDescription {
            get {
                return ResourceManager.GetString("ProfilePrivate_EmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile image will be resized and cropped to {0} pixels width and height. File size should not exceed {1} MB..
        /// </summary>
        public static string ProfilePublic_ProfilePhotoDescription {
            get {
                return ResourceManager.GetString("ProfilePublic_ProfilePhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share something about youself. Let people know about you!.
        /// </summary>
        public static string ProfilePublic_ShareAboutYourself {
            get {
                return ResourceManager.GetString("ProfilePublic_ShareAboutYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done!.
        /// </summary>
        public static string Register_AlmostDone {
            get {
                return ResourceManager.GetString("Register_AlmostDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string Signin_FinalizeSignin {
            get {
                return ResourceManager.GetString("Signin_FinalizeSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin_Signin {
            get {
                return ResourceManager.GetString("Signin_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string UserHome_Profile_Tab_Private {
            get {
                return ResourceManager.GetString("UserHome_Profile_Tab_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string UserHome_Profile_Tab_Public {
            get {
                return ResourceManager.GetString("UserHome_Profile_Tab_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkroom.
        /// </summary>
        public static string UserHome_Tab_Darkroom {
            get {
                return ResourceManager.GetString("UserHome_Tab_Darkroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string UserHome_Tab_You {
            get {
                return ResourceManager.GetString("UserHome_Tab_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string UserPublic_Tab_Favorites {
            get {
                return ResourceManager.GetString("UserPublic_Tab_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string UserPublic_Tab_Gallery {
            get {
                return ResourceManager.GetString("UserPublic_Tab_Gallery", resourceCulture);
            }
        }
    }
}
