//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Client.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string AuthMenu_SignIn {
            get {
                return ResourceManager.GetString("AuthMenu_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string AuthMenu_SignOut {
            get {
                return ResourceManager.GetString("AuthMenu_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My home.
        /// </summary>
        public static string AuthMenu_UserHome {
            get {
                return ResourceManager.GetString("AuthMenu_UserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register!.
        /// </summary>
        public static string Btn_Register {
            get {
                return ResourceManager.GetString("Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to register you in. Please, try one more time later..
        /// </summary>
        public static string EAPI_Auth_RegistrationError {
            get {
                return ResourceManager.GetString("EAPI_Auth_RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {UserName} is already taken. Please, select a different one..
        /// </summary>
        public static string EAPI_Auth_UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("EAPI_Auth_UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model state.
        /// </summary>
        public static string EAPI_InvalidModelState {
            get {
                return ResourceManager.GetString("EAPI_InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value(s) you provided is invalid!.
        /// </summary>
        public static string EAPI_InvalidValue {
            get {
                return ResourceManager.GetString("EAPI_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have encountered an error, while trying to execute your request :( Please, try one more time..
        /// </summary>
        public static string EAPI_Unknown {
            get {
                return ResourceManager.GetString("EAPI_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be min. {MinLength} and max. {MaxLength} characters long..
        /// </summary>
        public static string EAPI_ValueLength {
            get {
                return ResourceManager.GetString("EAPI_ValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, provide a value!.
        /// </summary>
        public static string EAPI_ValueRequired {
            get {
                return ResourceManager.GetString("EAPI_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters A-Z, a-z, numbers 0-9, dash and underscore are allowed! .
        /// </summary>
        public static string EC_Auth_InvalidUserName {
            get {
                return ResourceManager.GetString("EC_Auth_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken. Please, select a different one..
        /// </summary>
        public static string EC_Auth_UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("EC_Auth_UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name should be min. 2 and max. 20 characters long..
        /// </summary>
        public static string EC_Auth_UserNameLength {
            get {
                return ResourceManager.GetString("EC_Auth_UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name will be displayed instead of username.
        /// </summary>
        public static string Hint_FullName {
            get {
                return ResourceManager.GetString("Hint_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Label_FullName {
            get {
                return ResourceManager.GetString("Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select your user name:.
        /// </summary>
        public static string Label_SelectUserName {
            get {
                return ResourceManager.GetString("Label_SelectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MainMenu_Gallery {
            get {
                return ResourceManager.GetString("MainMenu_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done!.
        /// </summary>
        public static string Register_AlmostDone {
            get {
                return ResourceManager.GetString("Register_AlmostDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string Signin_FinalizeSignin {
            get {
                return ResourceManager.GetString("Signin_FinalizeSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin_Signin {
            get {
                return ResourceManager.GetString("Signin_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string UserHome_Profile_Tab_Private {
            get {
                return ResourceManager.GetString("UserHome_Profile_Tab_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string UserHome_Profile_Tab_Public {
            get {
                return ResourceManager.GetString("UserHome_Profile_Tab_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkroom.
        /// </summary>
        public static string UserHome_Tab_Darkroom {
            get {
                return ResourceManager.GetString("UserHome_Tab_Darkroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string UserPublic_Tab_Favorites {
            get {
                return ResourceManager.GetString("UserPublic_Tab_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string UserPublic_Tab_Gallery {
            get {
                return ResourceManager.GetString("UserPublic_Tab_Gallery", resourceCulture);
            }
        }
    }
}
